"""Initial migration

Revision ID: 01b39c33b171
Revises: None
Create Date: 2016-09-23 21:14:06.368989

"""

# revision identifiers, used by Alembic.
revision = '01b39c33b171'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('washrooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('has_wheelchair_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('washroom_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cleanliness', sa.Integer(), nullable=True),
    sa.Column('privacy', sa.Integer(), nullable=True),
    sa.Column('safety', sa.Integer(), nullable=True),
    sa.Column('accessibility', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['washroom_id'], ['washrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_features',
    sa.Column('review', sa.BigInteger(), nullable=True),
    sa.Column('feature_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['review'], ['reviews.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_features')
    op.drop_table('reviews')
    op.drop_table('washrooms')
    op.drop_table('users')
    op.drop_table('features')
    ### end Alembic commands ###
