"""Rename user_features to review_features

Revision ID: b5991175a9a9
Revises: d3ba2c7254eb
Create Date: 2016-09-24 19:46:36.630387

"""

# revision identifiers, used by Alembic.
revision = 'b5991175a9a9'
down_revision = 'd3ba2c7254eb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_features',
    sa.Column('review', sa.BigInteger(), nullable=True),
    sa.Column('feature_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['review'], ['reviews.id'], )
    )
    op.drop_table('user_features')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_features',
    sa.Column('review', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('feature_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name='user_features_ibfk_1'),
    sa.ForeignKeyConstraint(['review'], ['reviews.id'], name='user_features_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('review_features')
    ### end Alembic commands ###
